# Numpy

In [11]:
import numpy as np

In [ ]:
%timeit  # to time any operation for comparision

In [13]:
a = np.array([1,2,3,4])

In [14]:
type(a)

numpy.ndarray

In [15]:
b = np.array((3,4,5))

In [16]:
print(b)
type(b)

[3 4 5]


numpy.ndarray

In [17]:
x = np.zeros((3,4))
print (x)   #rank od 2 ----2d array
type(x)
x.shape

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


(3, 4)

In [18]:
y = np.ones((3,4), dtype =np.int16)
print(y)
y.shape

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


(3, 4)

In [17]:
z = np.zeros((2,3,4))
print (z)   #rank od 3 ----3d array
type(z)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


numpy.ndarray

In [18]:
y = np.ones((3,4), dtype =np.float64)
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
z = np.full((3,4), 101)
print(z)

[[101 101 101 101]
 [101 101 101 101]
 [101 101 101 101]]


In [22]:
pi = np.full((3,4), np.pi)
print(pi)

[[3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265]]


In [24]:
#np.arange ------Starts with till last number
np.arange(10,30)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [25]:
np.arange(10,30, 4)

array([10, 14, 18, 22, 26])

In [27]:
np.arange(0,1.1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [28]:
x = [
    [
        [1],
        [1],
        [1],
        [1]],
    [
        [1],
        [1],
        [1],
        [1]]
]

In [31]:
xx= np.array(x)
xx.shape

(2, 4, 1)

In [34]:
#linear space
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [37]:
np.linspace(1, 10, 25)

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

In [40]:
x= np.random.rand(2,3)
print(x, type(x))

[[0.55982196 0.43083549 0.33320771]
 [0.7879723  0.39747154 0.1353686 ]] <class 'numpy.ndarray'>


In [41]:
x = np.empty((2,3))

In [42]:
x

array([[0.55982196, 0.43083549, 0.33320771],
       [0.7879723 , 0.39747154, 0.1353686 ]])

In [43]:
c = np.arange(1,5)
c

array([1, 2, 3, 4])

In [44]:
c.dtype

dtype('int64')

In [45]:
c.itemsize

8

In [46]:
a = np.arange(6)

In [47]:
a

array([0, 1, 2, 3, 4, 5])

In [50]:
b = a.reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


In [51]:
b = a.reshape(2,2)
print(b)

ValueError: cannot reshape array of size 6 into shape (2,2)

In [58]:
a = np.arange(1,15,2)
print (a)

[ 1  3  5  7  9 11 13]


In [59]:
a[4]

9

In [61]:
print(a[2:5])

[5 7 9]


In [63]:
print(a[2::2])
print(a[2::3])

[ 5  9 13]
[ 5 11]


In [64]:
print(a[::-1])

[13 11  9  7  5  3  1]


In [65]:
a[2:5] = -1
print(a)

[ 1  3 -1 -1 -1 11 13]


In [66]:
a[:] = 0
print(a)

[0 0 0 0 0 0 0]


In [67]:
# Carefull update
a = np.array ([1,3,6,9,12,15,18,21,22])
print(a)

a_slice = a[4:]
print(a_slice)

a_slice[1:5]=100
print(a_slice)

print(a)

[ 1  3  6  9 12 15 18 21 22]
[12 15 18 21 22]
[ 12 100 100 100 100]
[  1   3   6   9  12 100 100 100 100]


In [69]:
a = np.array ([1,3,6,9,12,15,18,21,22])
print(a)

a_slice = a[4:].copy()   #copy
print(a_slice)

a_slice[1:5]=100
print(a_slice)   #update

print(a)         #unchanged

[ 1  3  6  9 12 15 18 21 22]
[12 15 18 21 22]
[ 12 100 100 100 100]
[ 1  3  6  9 12 15 18 21 22]


In [19]:
x = np.random.rand(4,5)
print(x)

[[0.17621011 0.33060469 0.11805626 0.6351815  0.08417987]
 [0.4253525  0.6490603  0.80735235 0.47853217 0.85051684]
 [0.33766622 0.69653328 0.04960363 0.32713798 0.84858295]
 [0.98328933 0.29309959 0.37138557 0.00774259 0.50552709]]


In [20]:
x[1]     # row

array([0.4253525 , 0.6490603 , 0.80735235, 0.47853217, 0.85051684])

In [21]:
x[1, 0]    #row/columns

0.4253525001344627

In [26]:
x [0:1, 0:4,]  # [ Row:Row , Column: Column]

array([[0.17621011, 0.33060469, 0.11805626, 0.6351815 ]])

In [32]:
a = np.arange(12).reshape(3,4)
print (a)

row_on = np.array([True, False, True])

print(row_on)

a[row_on]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ True False  True]


array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [81]:
a = np.array([20, 30, 40 , 50])
print(a)
b= np.arange(4)
print(b)
c = a+b
print(c)

[20 30 40 50]
[0 1 2 3]
[20 31 42 53]


In [4]:
import numpy as np
A = np.array ([[1,1],
              [0,1]])
B = np.array ([[2,0],
              [3,4]])

print(A*B)     # element wise product


print('------------------------------------')

print (([[1*2,1*0],
              [0*3,1*4]]))

[[2 0]
 [0 4]]
------------------------------------
[[2, 0], [0, 4]]


In [10]:

print(np.dot(A,B))

print('------------------------------------')

print (([[1*2+1*3,1*0+1*4],[0*2+1*3, 0*0+1*4]]))

[[5 4]
 [3 4]]
------------------------------------
[[5, 4], [3, 4]]


In [1]:
# Vector is defined by magnitude and direction
# vector = list of scalars

# Using vectors is machine learning

# X =  f1  f2  f3  f4
#   = [10, 12, 23, 40] -------Features as vectror

# Glove Vectors
# Queen - women + man = King
# relationship between Man & Women has same with King & Queen


In [2]:
# numpy.array([1, 1, 1, 1])

##### Broadcasting in Numpy Array

##### 2 rules of broadcasting

###### 1st rule
First rule of Broadcasting

[[[1, 3 ]]] + [5] [[[6, 8]]]

Shape (1, 1, 2) (1, ) (1, 1, 2)

If the arrays do not have the same rank, then a 1 will be
prepended to the smaller ranking arrays until their ranks match.



In [41]:
a = np.arange(6).reshape(2,3)
print("A = ",a)
b = np.array([1])
print("B = ", b)
c = a + b
print(c)

A =  [[0 1 2]
 [3 4 5]]
B =  [1]
[[1 2 3]
 [4 5 6]]


In [42]:
c = a-b
print(c)

[[-1  0  1]
 [ 2  3  4]]


In [44]:
a = np.array([[1]])
print("A = ",a, "Shape = ",a.shape)
b = np.array([1])
print("B = ", b, "Shape = ",b.shape)
c = a+b
print("C = " , c,"Shape = ", c.shape)

A =  [[1]] Shape =  (1, 1)
B =  [1] Shape =  (1,)
C =  [[2]] Shape =  (1, 1)


##### 2nd rule
<img src="https://s3.amazonaws.com/cloudxlab/static/images/course/numpy_pandas_for_ml/Broacasting_2_rule.png" alt="drawing" width="500"/>

In [47]:
k = np.arange(6).reshape(2, 3)
k

k + [100, 200, 300]


array([[100, 201, 302],
       [103, 204, 305]])

In [52]:
# Python array
a - [1,2,3,4,5]
a.mean()

1.0

In [55]:
#numpy array
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])  # sum of all elements/count
print("mean =", a.mean())

mean = 6.766666666666667


Similar to mean there are other ndarray methods which can be
used for various computations.

* min - returns the minimum element in the ndarray
* max - returns the maximum element in the ndarray
* sum - returns the sum of the elements in the ndarray
* prod - returns the product of the elements in the ndarray
* std - returns the standard deviation of the elements in the ndarray.
* var - returns the variance of the elements in the ndarray.

In [56]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])

for func in (a.min, a.max, a.sum, a.prod, a.std,a.var):
    print(func.__name__, "=", func())

min = -2.5
max = 12.0
sum = 40.6
prod = -71610.0
std = 5.084835843520964
var = 25.855555555555554


In [57]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [58]:
c.sum(axis=0) # sum across matrices

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [59]:
# Important about numpy sum
a= np.array ([[1,2,3],
             [4,5,6]])
b= np.array ([[.1,.2,.3],
             [.4,.5,.6]])

In [60]:
a+b

array([[1.1, 2.2, 3.3],
       [4.4, 5.5, 6.6]])

In [63]:
a= np.array ([[1,2,3],
             [4,5,6]])
a.sum()

21

In [64]:
a.sum(axis = 0)

array([5, 7, 9])

In [65]:
a.sum(axis = 1)

array([ 6, 15])

In [66]:
# Transpose
>>> m1 = np.arange(6).reshape(2,3)
>>> m1
>>> m1.T

array([[0, 3],
       [1, 4],
       [2, 5]])

#### Solving a system of linear scalar equations
2x + 6y = 6
5x + 3y = -9

In [67]:
from numpy import linalg

In [68]:
coeffs = np.array([[2, 6], [5, 3]]) #2x + 6y = 6 5x + 3y = -9
depvars = np.array([6, -9])
solution = linalg.solve(coeffs, depvars)
solution

array([-3.,  2.])

#### Solving a system of linear scalar equations

In [69]:
coeffs.dot(solution), depvars

(array([ 6., -9.]), array([ 6, -9]))