## Objective: Learning to solve basic Python problems


* Tackle few simple problems relvant to AI/ML
    - Break a problem into smaller sub-problems.
    - Connecting the dots from sub-problems to coding-concepts.
    - Code-walkthrough + Putting it all together.
    - More focus on common errors and mistakes + reading function reference + * fixing bugs
    - Exercise-problems for practice.
    - Introduce new concepts as we need.
    - Good programmers may not benifit much from this session.
    

### Problem 1: Add two randomly generated NumPy matrices using loops 
    - Sub-problems
    - Subproblems ---> coding concepts
    - Code-walkthrough + Mistakes
    - Exercise: Add two randomly generated NumPy 3D-matrices(tensor) using loops 

In [1]:
# create random matrix A1 of size 5X4.
### Google " numpy create random matrices " & Read through the top 4-5 links
### https://www.codespeedy.com/how-to-create-matrix-of-random-numbers-in-python-numpy/

import numpy as np
A1 = np.random.rand(5,4)  #(rows, Columns)

# read documentation to understand the params. Google "np.random.rand reference" ---> https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.rand.html

##COMMON-ERROR: np.random.rand(4,5)
##COMMON_ERROR: 

print(A1) # always print to ensure that everyhitng works fine.

print(A1.shape)


[[0.11419109 0.04090205 0.6744976  0.12569158]
 [0.37080561 0.94594833 0.22674558 0.16411151]
 [0.89926256 0.75835048 0.66838625 0.48044131]
 [0.98262586 0.12581884 0.03188257 0.51798177]
 [0.55870847 0.23684287 0.88246898 0.27068062]]
(5, 4)


In [2]:
print(A1.shape()); #COMMON-ERROR

TypeError: 'tuple' object is not callable

In [ ]:
print(A1.type); # COMMON-ERROR

In [3]:
print(type(A1));

<class 'numpy.ndarray'>


In [4]:
# Read through the attributes and methods in numpy.ndarray class
## Google "numpy.ndarray" ---> https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html

## Pre-Google programmers: Read reference docs.

In [5]:
# Create random Matrix A2
A2 = np.random.rand(5,4);

print(A2);

[[0.60978144 0.10047343 0.10608134 0.52186963]
 [0.50175274 0.73723035 0.29758813 0.53364459]
 [0.64007945 0.13759513 0.36864652 0.32285154]
 [0.49424465 0.28593887 0.48683157 0.43318618]
 [0.05378806 0.0447652  0.36694029 0.16489729]]


In [6]:
# Add element wise using loops A1+A2 = B

## Google "Accessing i,j th element in an ndarray" ---> https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html
print(A1[2,3]);


0.4804413128856596


In [7]:
print(A1(2,3)); #COMMON_ERROR >>>>>>>> print(A1[2,3]) or print(A1[(2,3)])

TypeError: 'numpy.ndarray' object is not callable

In [8]:
B= A1+A2; # using + operator on ndarrays
print(B); 

[[0.72397253 0.14137549 0.78057895 0.64756121]
 [0.87255835 1.68317868 0.52433371 0.69775611]
 [1.53934201 0.89594561 1.03703277 0.80329285]
 [1.4768705  0.41175771 0.51871414 0.95116796]
 [0.61249653 0.28160808 1.24940927 0.43557792]]


In [9]:
(r,c) = A1.shape;
print(r,c)

5 4


In [10]:
#B[i,j] = A1[i,j] + A2 [i,j] 

for i in range(r):
    for j in range(c):
        B[i,j] = A1[i,j] + A2[i,j];
        
print(B)

[[0.72397253 0.14137549 0.78057895 0.64756121]
 [0.87255835 1.68317868 0.52433371 0.69775611]
 [1.53934201 0.89594561 1.03703277 0.80329285]
 [1.4768705  0.41175771 0.51871414 0.95116796]
 [0.61249653 0.28160808 1.24940927 0.43557792]]


In [11]:
# OPTIMIZATION: Pre-allocate matrix B
B = np.zeros(5,4); # COMMON-ERROR

TypeError: Cannot interpret '4' as a data type

In [12]:
B = np.zeros((5,4))
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
#Google "np.zeros" ---> https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html


for i in range(r): # same code as earlier
    for j in range(c):
        B[i,j] = A1[i,j] + A2[i,j];
        
print(B)

[[0.72397253 0.14137549 0.78057895 0.64756121]
 [0.87255835 1.68317868 0.52433371 0.69775611]
 [1.53934201 0.89594561 1.03703277 0.80329285]
 [1.4768705  0.41175771 0.51871414 0.95116796]
 [0.61249653 0.28160808 1.24940927 0.43557792]]


In [14]:
# Time Complexity: ?  O(r * c)

# Space Complxiety: ? O(1)   ---we should not include i/p & o/p space

#### Exercise: Add two randomly generated NumPy 3D-matrices(tensor) using loops 

HINT: B[i,j,k] = A1[i,j,k] + A2[i,j,k]
****************************************************************************************************************
****************************************************************************************************************
****************************************************************************************************************

In [15]:
A1 = np.random.rand(2, 5,4,)  #( dimension, rows, Columns)


A2 = np.random.rand(2, 5, 4);

B = np.zeros((2,5,4))

d,r,c = A1.shape
for k in range(d):
    for i in range(r): # same code as earlier
        for j in range(c):
            B[k,i,j] = A1[k,i,j] + A2[k,i,j];
        
print(B)

[[[0.24786776 1.4136874  1.61807115 0.84495236]
  [1.13478853 0.81959093 1.4843208  0.35647493]
  [1.17654991 1.01036462 1.00011305 1.17683889]
  [0.66221768 1.11841415 0.60526931 0.80642776]
  [0.67525313 1.7720758  0.24770592 1.51785792]]

 [[0.77957268 1.31336045 0.76760056 1.91602739]
  [1.07563245 0.36612403 0.86691378 0.69305726]
  [1.59943421 0.61865248 0.85998634 1.14223012]
  [1.17358639 1.16740678 1.24624596 0.44413292]
  [0.94805791 0.59213453 1.43807366 0.82219936]]]


### Problem 2: Find if a given 2D-point is inside (or) outside a circle 
    - Subproblems.
    - Subproblems --> coding concepts.
    - putting it all together.
    - Exercise: Find if a given 2D point is inside (or) outside a rectangle ? 
   

In [16]:

## input circle (C) and point(P)

# input circle params
# Google " input multiple values python 3" ---> https://www.geeksforgeeks.org/input-multiple-values-user-one-line-python/
print("Enter Cx, Cy, r:");
(Cx, Cy, r) = raw_input().split();

print(Cx, Cy, r); # always cross check using print statements

# raw input not in Python3

Enter Cx, Cy, r:


NameError: name 'raw_input' is not defined

In [41]:
# input circle params
## Google "python input multiple values in single line" ----> https://www.tutorialspoint.com/how-to-input-multiple-values-from-user-in-one-line-in-python
## TRY MULTIPLE APPROACHES and learn from each attempt.

# Cx, Cy, r = input("Enter Cx, Cy, r:").split(); #>>>> not working

Cx, Cy, r = map(float, input().split())
#Cx, Cy, r = input(), input(), input()
print(Cx, Cy,r)

0 0 5
0.0 0.0 5.0


In [42]:
# Google " SyntaxError: invalid syntax input Python3 string" --> https://stackoverflow.com/questions/25174925/syntax-error-for-input
#Cx, Cy, r = raw_input("Enter Cx, Cy, r:").split();
print(type(Cx))

<class 'float'>


In [ ]:
print(Cx, Cy,r)

In [ ]:
# Input Px, Py

Px, Py = map(float, input("Enter Px, Py:").split())
print(Px, Py);

In [34]:
# # Check if P lies in C.
# d = ( (Cx-Px)**2 + (Cy-Py)**2 )   # missing sqrt
# print(d);

# if d<r:
#     print("P in C")
# else:
#     print("P NOT in C")

2.0
P in C


In [35]:
# Check if P lies in C.

## String to Float. Very important to note that split() returns Strings
Cx = float(Cx);
Cy = float(Cy);
r =float(r);
Px= float(Px);
Py = float(Py);

import math 

d = math.sqrt( (Cx-Px)**2 + (Cy-Py)**2 )
print(d);

if d<r:
    print("P in C")
else:
    print("P NOT in C")

1.4142135623730951
P in C


#### Exercise: Find if a point is inside or outside a rectangle.

HINT: How do you represent a rectangle?

********************************************
********************************************
********************************************

In [7]:
#solution1

# TRx,y == top right || BLx,y == Bottom left || Px,y == Point
TRx, TRy = map(float, input("Enter TRx, TRy:").split())
BLx, BLy = map(float, input("Enter BLx, BLy :").split())
Px, Py = map(float, input("Enter Px, Py:").split())

def in_Rectangle(TRx, TRy,BLx, BLy, Px, Py ) :
    if (Px > BLx and Px < TRx and Py > BLy and Py < TRy ):
          return True
    else :
          return False
in_Rectangle(TRx, TRy,BLx, BLy, Px, Py)

#Solution 2: We can use Array

# def solve(bl, tr, p) :
#    if (p[0] > bl[0] and p[0] < tr[0] and p[1] > bl[1] and p[1] < tr[1]) :
#       return True
#    else :
#       return False
# bottom_left = (1, 1)
# top_right = (8, 5)
# point = (5, 4)
# print(solve(bottom_left, top_right, point))

Enter TRx, TRy:8 5
Enter BLx, BLy :1 1 
Enter Px, Py:5 4


True

### Problem 3: NumPy ndarray manupualtion operations


In [9]:
import numpy as np
# 1. Reshape matrices: Very COMMON-ERRORS in Assignments
A = np.random.rand(5,4);
print(A);


[[0.02824635 0.06020137 0.99766116 0.19883466]
 [0.55753494 0.16229568 0.46729426 0.78151506]
 [0.41144438 0.67090354 0.05785613 0.52656697]
 [0.75480889 0.85201136 0.71817891 0.60641832]
 [0.65058428 0.06063225 0.27023775 0.36227192]]


In [10]:
## reshape into a vector row-major-order
###https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html 
### Patiently read the documentation and try alternaive params
print( np.reshape(A, 20, 'C'))  # 'C' >>> Row major order


[0.02824635 0.06020137 0.99766116 0.19883466 0.55753494 0.16229568
 0.46729426 0.78151506 0.41144438 0.67090354 0.05785613 0.52656697
 0.75480889 0.85201136 0.71817891 0.60641832 0.65058428 0.06063225
 0.27023775 0.36227192]


In [12]:
print( np.reshape(A, 20, 'F')) # Fortran >> Column major order

[0.02824635 0.55753494 0.41144438 0.75480889 0.65058428 0.06020137
 0.16229568 0.67090354 0.85201136 0.06063225 0.99766116 0.46729426
 0.05785613 0.71817891 0.27023775 0.19883466 0.78151506 0.52656697
 0.60641832 0.36227192]


In [13]:
print( np.reshape(A, (4,5), 'C'))

[[0.02824635 0.06020137 0.99766116 0.19883466 0.55753494]
 [0.16229568 0.46729426 0.78151506 0.41144438 0.67090354]
 [0.05785613 0.52656697 0.75480889 0.85201136 0.71817891]
 [0.60641832 0.65058428 0.06063225 0.27023775 0.36227192]]


In [14]:
print( np.reshape(A, (4,-1), 'C'))

[[0.02824635 0.06020137 0.99766116 0.19883466 0.55753494]
 [0.16229568 0.46729426 0.78151506 0.41144438 0.67090354]
 [0.05785613 0.52656697 0.75480889 0.85201136 0.71817891]
 [0.60641832 0.65058428 0.06063225 0.27023775 0.36227192]]


In [15]:
print( np.reshape(A, (-1,5), 'C'))

[[0.02824635 0.06020137 0.99766116 0.19883466 0.55753494]
 [0.16229568 0.46729426 0.78151506 0.41144438 0.67090354]
 [0.05785613 0.52656697 0.75480889 0.85201136 0.71817891]
 [0.60641832 0.65058428 0.06063225 0.27023775 0.36227192]]


In [16]:
print( np.reshape(A, (4,6), 'C'))

ValueError: cannot reshape array of size 20 into shape (4,6)

#### Exercise: take a tensor of size 4X5X6 and convert it into a tensor of vector and matrix (10X12).

In [ ]:
#solution

A = np.random.rand(4,5,6)
print( np.reshape(A, (120), 'C'))     # 1d Vector
print( np.reshape(A, (10,12), 'C'))

In [23]:
#2. Stacking
A = np.random.rand(5,4);
print(A);

B= np.random.rand(5,2);
print(B)


[[0.51753849 0.00413627 0.93655    0.91733812]
 [0.43592759 0.75002353 0.03718398 0.90379814]
 [0.34974612 0.01534318 0.15905686 0.5169208 ]
 [0.28975018 0.96340479 0.20674238 0.04551855]
 [0.2000864  0.50675347 0.13491329 0.8155138 ]]
[[0.92995482 0.80144001]
 [0.01122398 0.05621959]
 [0.1093841  0.58537065]
 [0.32973121 0.14308711]
 [0.36078314 0.30275528]]


In [28]:
# C = [A B] ---Concatenating not sum
C = np.hstack(A, B);   # common Error
print(C)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [27]:
C = np.hstack((A, B)); # read documentation carefully
print(C)

[[0.51753849 0.00413627 0.93655    0.91733812 0.92995482 0.80144001]
 [0.43592759 0.75002353 0.03718398 0.90379814 0.01122398 0.05621959]
 [0.34974612 0.01534318 0.15905686 0.5169208  0.1093841  0.58537065]
 [0.28975018 0.96340479 0.20674238 0.04551855 0.32973121 0.14308711]
 [0.2000864  0.50675347 0.13491329 0.8155138  0.36078314 0.30275528]]


In [29]:
A = np.random.rand(5,4);
print(A);

B= np.random.rand(4,4);
print(B)

C = np.hstack((A, B));    # it will not work
print(C)

[[0.77326802 0.81269228 0.60098111 0.46023258]
 [0.62663729 0.78713075 0.10940695 0.42178044]
 [0.13473523 0.21678858 0.14777099 0.3850994 ]
 [0.14724069 0.40904938 0.69226529 0.62486113]
 [0.59430726 0.60971708 0.93863903 0.04979529]]
[[0.19195953 0.90176802 0.9955996  0.74124699]
 [0.98946978 0.56622796 0.5681176  0.4663762 ]
 [0.85796399 0.12332633 0.72738697 0.96431373]
 [0.93778038 0.65173834 0.95949048 0.85531819]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 4

In [30]:
A = np.random.rand(5,4);
print(A);

B= np.random.rand(4,4);
print(B)

C = np.vstack((A, B)); #Vertical stacking
print(C)

[[0.03507936 0.15424443 0.80269649 0.40071464]
 [0.08113523 0.51884121 0.71775139 0.42974313]
 [0.17256369 0.06623889 0.77193625 0.629401  ]
 [0.577798   0.96389228 0.77782471 0.76984967]
 [0.14827747 0.81750878 0.43498497 0.23984703]]
[[0.23969501 0.61135407 0.45771649 0.8063997 ]
 [0.64022292 0.31619828 0.03498183 0.1594187 ]
 [0.62658916 0.5885009  0.74380595 0.22780118]
 [0.92989567 0.15554295 0.98791541 0.19720931]]
[[0.03507936 0.15424443 0.80269649 0.40071464]
 [0.08113523 0.51884121 0.71775139 0.42974313]
 [0.17256369 0.06623889 0.77193625 0.629401  ]
 [0.577798   0.96389228 0.77782471 0.76984967]
 [0.14827747 0.81750878 0.43498497 0.23984703]
 [0.23969501 0.61135407 0.45771649 0.8063997 ]
 [0.64022292 0.31619828 0.03498183 0.1594187 ]
 [0.62658916 0.5885009  0.74380595 0.22780118]
 [0.92989567 0.15554295 0.98791541 0.19720931]]


In [31]:
# 3D tensors
A = np.random.rand(5,4,3); # (height, width, colors) in images is a good way to think of this
print(A.shape);

B= np.random.rand(5,3,3);
print(B.shape)

C = np.hstack((A, B));
print(C.shape)

(5, 4, 3)
(5, 3, 3)
(5, 7, 3)


In [32]:
# 3D tensors
A = np.random.rand(5,4,3);
print(A.shape);

B= np.random.rand(4,3,3);
print(B.shape)

C = np.hstack((A, B));
print(C.shape)

(5, 4, 3)
(4, 3, 3)


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 4

In [33]:
# 3D tensors
A = np.random.rand(5,4,3);
print(A.shape);

B= np.random.rand(5,4,2);
print(B.shape)

C = np.hstack((A, B));
print(C.shape)

(5, 4, 3)
(5, 4, 2)


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 3 and the array at index 1 has size 2

In [34]:
# 3D tensors vstack
A = np.random.rand(5,4,3); # (height, width, colors) in images
print(A.shape);

B= np.random.rand(2,4,3);
print(B.shape)

C = np.vstack((A, B));
print(C.shape)

(5, 4, 3)
(2, 4, 3)
(7, 4, 3)


#### Exercise: Achieve the above tranaomfrs using numpy.concatenate [https://numpy.org/doc/1.18/reference/generated/numpy.concatenate.html#numpy.concatenate]
***********
***********
* a = np.array([[1, 2], [3, 4]])
* b = np.array([[5, 6]])
* np.concatenate((a, b), axis=0)
* array([[1, 2],
       [3, 4],
       [5, 6]])
* np.concatenate((a, b.T), axis=1)
* array([[1, 2, 5],
       [3, 4, 6]])
* np.concatenate((a, b), axis=None)
* array([1, 2, 3, 4, 5, 6])
***********
***********


In [35]:
C = np.concatenate((A, B), axis=0)
print(C.shape)

(7, 4, 3)


### Problem-4: Find peaks/max in an list
- problem definition


In [36]:

A = [1,3,4,5,7,6,4,5,10,1];
print(A)

[1, 3, 4, 5, 7, 6, 4, 5, 10, 1]


In [37]:
# Peaks: 7,10
# Peak: A[i-1] <= A[i] >= A[i+1]

for i in range(1, A.size - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

AttributeError: 'list' object has no attribute 'size'

In [38]:
print(len(A));

10


In [39]:
for i in range(1, len(A) - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

7
10


In [ ]:
# There is a bug in the above solution. Find it...


In [40]:
A = [11,3,4,5,7,6,4,5,10,15];

for i in range(1, len(A) - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

7


In [41]:
# what about 11 and 15?

# boundary case
if A[0] >= A[1]:
    print(A[0])
    
for i in range(1, len(A) - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

# boundary case
if A[len(A)-1] >= A[len(A)-2]:
    print(A[len(A)-1])


11
7
15


In [ ]:
# LESSON: Donot forget boundary cases

#Question: Time Complexity = ?

#### Exercise: 
1. Find peaks which are max values in a window of size 2 on both sides.
2. Use scipy.signal.find_peaks [https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html]

Additioanl reading: More efficient algos @ http://courses.csail.mit.edu/6.006/spring11/lectures/lec02.pdf

### Problem 5: Permutations of a list
- Problem definition: lst = [1,2,3]

In [ ]:
# Using libraries
from itertools import permutations 
  
p = permutations([1, 2, 3]) # refer: https://docs.python.org/3/library/itertools.html#itertools.permutations

# what is an iterable in Python [https://www.pythonlikeyoumeanit.com/Module2_EssentialsOfPython/Iterables.html]

# print the permutations
for i in list(p): 
    print i 

In [ ]:
# No fun!
# Write your own code. Any suggestions?
# Break the problem into smaller sub-problems

In [ ]:
[1,2,3]
[1,3,2]
[2,1,3]
[2,3,1]
[3,1,2]
[3,2,1]

In [ ]:
# source: https://stackoverflow.com/questions/13109274/python-recursion-permutations

def permutation(s):
   if len(s) == 1:
     return [s]

   perm_list = [] # resulting list
   for a in s:
     remaining_elements = [x for x in s if x != a]
     z = permutation(remaining_elements) # permutations of sub-list

     for t in z:
       perm_list.append([a] + t)

   return perm_list

s = [1,2,3];
p = permutation(s);
print(p)

#### Exercise: [Combinations] All possible ways to pick 3 elements out of 5 elements

- HINT: Use recursion.
- Google "combinations in Python"

### Practice, practice and practice..

- Optional  Assignments at AAIC: https://go.aws/2JrmV4A [Functions] , https://drive.google.com/file/d/1VB3wJSt_Mq0HLP9uaqgsZBR4BLMFnkmY/view [Pandas]

- Basic Python: https://www.geeksforgeeks.org/python-programming-examples/
- NumPy: https://www.w3resource.com/python-exercises/numpy/index.php
